### ISSUE TITLE
latest (6.0.36) webpage 404

### ISSUE THREAD

**Issue by SubtleMuffin** [jacobalberty/unifi-docker#385]
### Host operating system

Ubuntu focal, 5.4.0-53-generic; Docker version 19.03.13, build 4484c46d9d

### What tag are you using

`latest` (6.0.36)

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

```shell
sudo docker-compose down && sudo docker-compose rm
sudo docker system prune --all
sudo docker-compose up
```

### What do you expect to happen?

Boot up as expected.

### What actually happens?

404...

### Log

```shell
> sudo docker-compose up
Creating network "unifi_unifi" with the default driver
Creating network "unifi_default" with the default driver
Pulling mongo (mongo:3.6)...
3.6: Pulling from library/mongo
2c11b7cecaa5: Pull complete
04637fa56252: Pull complete
d6e6af23a0f3: Pull complete
b4a424de92ad: Pull complete
cfdc37f645f1: Pull complete
42052a7ad84f: Pull complete
877ff6eda0f8: Pull complete
82bec5181c8b: Pull complete
299eaf21db23: Pull complete
6b9fd2f8fadc: Pull complete
9b849304bc27: Pull complete
70fbb6f6f7dc: Pull complete
5f3192050bf0: Pull complete
Digest: sha256:7ee1e679748051590cfc328c8e773775ccc3116ca1ece1def188b4e52d8a84ed
Status: Downloaded newer image for mongo:3.6
Pulling controller (jacobalberty/unifi:latest)...
latest: Pulling from jacobalberty/unifi
171857c49d0f: Pull complete
419640447d26: Pull complete
61e52f862619: Pull complete
2f026b1824b3: Pull complete
66c40ce6b82a: Pull complete
a06d73ffd6b3: Pull complete
fbda1e304fa6: Pull complete
88bebe4d5ae7: Pull complete
56ea37089ac5: Pull complete
ce1961e4565c: Pull complete
f77c78ba37be: Pull complete
087b37181761: Pull complete
efd7f957c406: Pull complete
4022de303640: Pull complete
Digest: sha256:29b970b2daf41f6756d5f06f7222989f5ae6f17c3ea3030f0488d982d20bd2a6
Status: Downloaded newer image for jacobalberty/unifi:latest
Pulling logs (bash:)...
latest: Pulling from library/bash
188c0c94c7c5: Pull complete
94387ca39817: Pull complete
efe7174943e6: Pull complete
Digest: sha256:01fad26fa8ba21bce6e8c47222acfdb54649957f1e86d53a0c8e03360271abf6
Status: Downloaded newer image for bash:latest
Creating unifi_mongo ... done
Creating unifi_controller ... done
Creating unifi_logs       ... done
Attaching to unifi_mongo, unifi_controller, unifi_logs
controller_1  | sed: couldn't open temporary file /unifi/data/sedhlEBNf: Permission denied
controller_1  | sed: couldn't open temporary file /unifi/data/sedLkFHvj: Permission denied
logs_1        | [2020-10-21T02:22:52,629] <localhost-startStop-1> INFO  system - [server backup][BACKUP] end
logs_1        | [2020-10-21T02:22:52,850] <localhost-startStop-1> INFO  db     - DB migration to version (6.0.22) is complete.
logs_1        | [2020-10-21T02:22:55,792] <localhost-startStop-1> INFO  webrtc - WebRTC library version: EvoStream Media Server (www.evostream.com) build v2.9.1 - Gladiato                                                                                                                        r - (built for Debian-8.2.0-x86_64 on 2020-02-05T23:33:19.000) OpenSSL version: 1.1.1d usrsctp version: v0.1.2 compiled on machine: Linux debian-8-2-0-64 3.16.0-6-amd64 #1                                                                                                                         SMP Debian 3.16.57-2 (2018-07-14) x86_64 GNU/Linux
logs_1        | [2020-10-21T02:22:56,709] <localhost-startStop-1> INFO  remote - Directory '/usr/lib/unifi/logs/remote' present
logs_1        | [2020-10-21T02:24:26,042] <ws-notify> WARN  api    - unable to send over websocket java.lang.IllegalStateException: The WebSocket session [2] has been clos                                                                                                                        ed and no method (apart from close()) may be called on a closed session
logs_1        | [2020-10-21T02:24:26,044] <ws-notify> WARN  api    - unable to send over websocket java.lang.IllegalStateException: The WebSocket session [2] has been clos                                                                                                                        ed and no method (apart from close()) may be called on a closed session
logs_1        | [2020-10-21T02:24:26,045] <ws-notify> WARN  api    - unable to send over websocket java.lang.IllegalStateException: The WebSocket session [2] has been clos                                                                                                                        ed and no method (apart from close()) may be called on a closed session
logs_1        | [2020-10-21T02:27:27,202] <ucare-device-check-task> WARN  ucare  - Device check failed: Cloud operation failed! RC=404, error: {"code":"NOT_FOUND","timesta                                                                                                                        mp":"1603247247"}
logs_1        | [2020-10-21T02:34:22,668] <webapi-56> WARN  api    - websocket session error:null
logs_1        | [2020-10-21T03:15:00,036] <schedule-optimize> INFO  schedule - Not forcing multicast block on any SSIDs since none had >= 100 clients in last hour
mongo_1       | 2020-11-20T05:14:45.192+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=0c4fcc708d04
mongo_1       | 2020-11-20T05:14:45.192+0000 I CONTROL  [initandlisten] db version v3.6.21
mongo_1       | 2020-11-20T05:14:45.192+0000 I CONTROL  [initandlisten] git version: 1cd2db51dce4b16f4bc97a75056269df0dc0bddb
mongo_1       | 2020-11-20T05:14:45.192+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
controller_1  | sed: couldn't open temporary file /unifi/data/sedObs9sh: Permission denied
controller_1  | sed: couldn't open temporary file /unifi/data/sedFKZWfl: Permission denied
controller_1  | [2020-11-20 05:14:46,533] <docker-entrypoint> Starting unifi controller service.
mongo_1       | 2020-11-20T05:14:45.192+0000 I CONTROL  [initandlisten] allocator: tcmalloc
mongo_1       | 2020-11-20T05:14:45.192+0000 I CONTROL  [initandlisten] modules: none
mongo_1       | 2020-11-20T05:14:45.192+0000 I CONTROL  [initandlisten] build environment:
mongo_1       | 2020-11-20T05:14:45.192+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
mongo_1       | 2020-11-20T05:14:45.192+0000 I CONTROL  [initandlisten]     distarch: x86_64
mongo_1       | 2020-11-20T05:14:45.192+0000 I CONTROL  [initandlisten]     target_arch: x86_64
mongo_1       | 2020-11-20T05:14:45.193+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true } }
mongo_1       | 2020-11-20T05:14:45.193+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active s                                                                                                                        torage engine to 'wiredTiger'.
mongo_1       | 2020-11-20T05:14:45.194+0000 I STORAGE  [initandlisten]
mongo_1       | 2020-11-20T05:14:45.194+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
mongo_1       | 2020-11-20T05:14:45.194+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
mongo_1       | 2020-11-20T05:14:45.194+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=3393M,cache_overflow=(file_max=0M),session_max=20000,evic                                                                                                                        tion=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),compatibility=(release="3.0",require_max="3.0"),log=(enabled=true,archive=true,path=journal,compress                                                                                                                        or=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
mongo_1       | 2020-11-20T05:14:46.886+0000 I STORAGE  [initandlisten] WiredTiger message [1605849286:886423][1:0x7fcc6a1d8a40], txn-recover: Main recovery loop: starting                                                                                                                         at 103/3102848
mongo_1       | 2020-11-20T05:14:47.296+0000 I STORAGE  [initandlisten] WiredTiger message [1605849287:296286][1:0x7fcc6a1d8a40], txn-recover: Recovering log 103 through 1                                                                                                                        04
mongo_1       | 2020-11-20T05:14:47.515+0000 I STORAGE  [initandlisten] WiredTiger message [1605849287:515312][1:0x7fcc6a1d8a40], txn-recover: Recovering log 104 through 1                                                                                                                        04
mongo_1       | 2020-11-20T05:14:47.717+0000 I STORAGE  [initandlisten] WiredTiger message [1605849287:717262][1:0x7fcc6a1d8a40], txn-recover: Set global recovery timestam                                                                                                                        p: 0
mongo_1       | 2020-11-20T05:14:47.749+0000 I CONTROL  [initandlisten]
mongo_1       | 2020-11-20T05:14:47.749+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
mongo_1       | 2020-11-20T05:14:47.749+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
mongo_1       | 2020-11-20T05:14:47.749+0000 I CONTROL  [initandlisten]
mongo_1       | 2020-11-20T05:14:47.782+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
mongo_1       | 2020-11-20T05:14:47.784+0000 I NETWORK  [initandlisten] listening via socket bound to 0.0.0.0
mongo_1       | 2020-11-20T05:14:47.784+0000 I NETWORK  [initandlisten] listening via socket bound to /tmp/mongodb-27017.sock
mongo_1       | 2020-11-20T05:14:47.784+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
controller_1  | 2020-11-20 05:14:48,480 main ERROR RollingFileManager (logs/server.log) java.io.FileNotFoundException: logs/server.log (Permission denied) java.io.FileNotF                                                                                                                        oundException: logs/server.log (Permission denied)
controller_1  |         at java.io.FileOutputStream.open0(Native Method)
controller_1  |         at java.io.FileOutputStream.open(FileOutputStream.java:270)
controller_1  |         at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
controller_1  |         at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
controller_1  |         at org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(RollingFileManager.java:671)
controller_1  |         at org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(RollingFileManager.java:641)
controller_1  |         at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:113)
controller_1  |         at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:100)
controller_1  |         at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:205)
controller_1  |         at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:146)
controller_1  |         at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:62)
controller_1  |         at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
controller_1  |         at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1002)
controller_1  |         at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:942)
controller_1  |         at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:934)
controller_1  |         at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:552)
controller_1  |         at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:241)
controller_1  |         at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:288)
controller_1  |         at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:618)
controller_1  |         at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:691)
controller_1  |         at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:708)
controller_1  |         at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)
controller_1  |         at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:153)
controller_1  |         at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
controller_1  |         at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
controller_1  |         at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:138)
controller_1  |         at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:45)
controller_1  |         at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:48)
controller_1  |         at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:30)
controller_1  |         at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:363)
controller_1  |         at com.ubnt.service.system.J.o00000(Unknown Source)
controller_1  |         at com.ubnt.service.system.J.<clinit>(Unknown Source)
controller_1  |         at com.ubnt.ace.Launcher.<clinit>(Unknown Source)
controller_1  |
controller_1  | 2020-11-20 05:14:48,496 main ERROR Could not create plugin of type class org.apache.logging.log4j.core.appender.RollingFileAppender for element RollingFile                                                                                                                        : java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory@4ae3c1cd] unable to create m                                                                                                                        anager for [logs/server.log] with data [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$FactoryData@29f69090[pattern=logs/server.log.%i, append=true, buf                                                                                                                        feredIO=true, bufferSize=8192, policy=SizeBasedTriggeringPolicy(size=10485760), strategy=DefaultRolloverStrategy(min=1, max=3, useMax=false), advertiseURI=null, layout=[%d                                                                                                                        {ISO8601}] <%t> %-5p %-6c{1} - %m%n, filePermissions=null, fileOwner=null]] java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.rolling                                                                                                                        .RollingFileManager$RollingFileManagerFactory@4ae3c1cd] unable to create manager for [logs/server.log] with data [org.apache.logging.log4j.core.appender.rolling.RollingFil                                                                                                                        eManager$FactoryData@29f69090[pattern=logs/server.log.%i, append=true, bufferedIO=true, bufferSize=8192, policy=SizeBasedTriggeringPolicy(size=10485760), strategy=DefaultR                                                                                                                        olloverStrategy(min=1, max=3, useMax=false), advertiseURI=null, layout=[%d{ISO8601}] <%t> %-5p %-6c{1} - %m%n, filePermissions=null, fileOwner=null]]
controller_1  |         at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:115)
controller_1  |         at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:100)
controller_1  |         at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:205)
controller_1  |         at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:146)
controller_1  |         at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:62)
controller_1  |         at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
controller_1  |         at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1002)
controller_1  |         at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:942)
controller_1  |         at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:934)
controller_1  |         at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:552)
controller_1  |         at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:241)
controller_1  |         at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:288)
controller_1  |         at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:618)
controller_1  |         at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:691)
controller_1  |         at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:708)
controller_1  |         at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)
controller_1  |         at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:153)
controller_1  |         at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
controller_1  |         at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
controller_1  |         at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:138)
controller_1  |         at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:45)
controller_1  |         at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:48)
controller_1  |         at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:30)
controller_1  |         at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:363)
controller_1  |         at com.ubnt.service.system.J.o00000(Unknown Source)
controller_1  |         at com.ubnt.service.system.J.<clinit>(Unknown Source)
controller_1  |         at com.ubnt.ace.Launcher.<clinit>(Unknown Source)
controller_1  |
controller_1  | 2020-11-20 05:14:48,501 main ERROR Unable to invoke factory method in class org.apache.logging.log4j.core.appender.RollingFileAppender for element RollingF                                                                                                                        ile: java.lang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appender.RollingFileAppender java.lang.IllegalStateException: No fact                                                                                                                        ory method found for class org.apache.logging.log4j.core.appender.RollingFileAppender
controller_1  |         at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.findFactoryMethod(PluginBuilder.java:234)
controller_1  |         at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:134)
controller_1  |         at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1002)
controller_1  |         at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:942)
controller_1  |         at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:934)
controller_1  |         at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:552)
controller_1  |         at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:241)
controller_1  |         at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:288)
controller_1  |         at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:618)
controller_1  |         at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:691)
controller_1  |         at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:708)
controller_1  |         at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)
controller_1  |         at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:153)
controller_1  |         at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
controller_1  |         at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
controller_1  |         at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:138)
controller_1  |         at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:45)
controller_1  |         at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:48)
controller_1  |         at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:30)
controller_1  |         at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:363)
controller_1  |         at com.ubnt.service.system.J.o00000(Unknown Source)
controller_1  |         at com.ubnt.service.system.J.<clinit>(Unknown Source)
controller_1  |         at com.ubnt.ace.Launcher.<clinit>(Unknown Source)
controller_1  |
controller_1  | 2020-11-20 05:14:49,044 main ERROR Null object returned for RollingFile in Appenders.
controller_1  | 2020-11-20 05:14:49,090 main ERROR Unable to locate appender "server_log" for logger config "root"
mongo_1       | 2020-11-20T05:14:58.066+0000 I NETWORK  [listener] connection accepted from 172.22.0.3:37734 #1 (1 connection now open)
mongo_1       | 2020-11-20T05:14:58.090+0000 I NETWORK  [conn1] received client metadata from 172.22.0.3:37734 conn1: { driver: { name: "mongo-java-driver", version: "3.4.                                                                                                                        3-dirty" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "5.4.0-53-generic" }, platform: "Java/Private Build/1.8.0_275-8u275-b01-0ubuntu1~18.04-b01"                                                                                                                         }
mongo_1       | 2020-11-20T05:14:58.131+0000 I NETWORK  [listener] connection accepted from 172.22.0.3:37736 #2 (2 connections now open)
mongo_1       | 2020-11-20T05:14:58.134+0000 I NETWORK  [conn2] received client metadata from 172.22.0.3:37736 conn2: { driver: { name: "mongo-java-driver", version: "3.4.                                                                                                                        3-dirty" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "5.4.0-53-generic" }, platform: "Java/Private Build/1.8.0_275-8u275-b01-0ubuntu1~18.04-b01"                                                                                                                         }
mongo_1       | 2020-11-20T05:14:58.963+0000 I NETWORK  [listener] connection accepted from 172.22.0.3:37738 #3 (3 connections now open)
mongo_1       | 2020-11-20T05:14:58.964+0000 I NETWORK  [conn3] received client metadata from 172.22.0.3:37738 conn3: { driver: { name: "mongo-java-driver", version: "3.4.                                                                                                                        3-dirty" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "5.4.0-53-generic" }, platform: "Java/Private Build/1.8.0_275-8u275-b01-0ubuntu1~18.04-b01"                                                                                                                         }
mongo_1       | 2020-11-20T05:14:58.971+0000 I NETWORK  [listener] connection accepted from 172.22.0.3:37740 #4 (4 connections now open)
mongo_1       | 2020-11-20T05:14:58.972+0000 I NETWORK  [conn4] received client metadata from 172.22.0.3:37740 conn4: { driver: { name: "mongo-java-driver", version: "3.4.                                                                                                                        3-dirty" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "5.4.0-53-generic" }, platform: "Java/Private Build/1.8.0_275-8u275-b01-0ubuntu1~18.04-b01"                                                                                                                         }
mongo_1       | 2020-11-20T05:14:59.189+0000 I NETWORK  [listener] connection accepted from 172.22.0.3:37742 #5 (5 connections now open)
mongo_1       | 2020-11-20T05:14:59.192+0000 I NETWORK  [conn5] received client metadata from 172.22.0.3:37742 conn5: { driver: { name: "mongo-java-driver", version: "3.4.                                                                                                                        3-dirty" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "5.4.0-53-generic" }, platform: "Java/Private Build/1.8.0_275-8u275-b01-0ubuntu1~18.04-b01"                                                                                                                         }
mongo_1       | 2020-11-20T05:14:59.984+0000 I NETWORK  [listener] connection accepted from 172.22.0.3:37744 #6 (6 connections now open)
mongo_1       | 2020-11-20T05:14:59.985+0000 I NETWORK  [conn6] received client metadata from 172.22.0.3:37744 conn6: { driver: { name: "mongo-java-driver", version: "3.4.                                                                                                                        3-dirty" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "5.4.0-53-generic" }, platform: "Java/Private Build/1.8.0_275-8u275-b01-0ubuntu1~18.04-b01"                                                                                                                         }
mongo_1       | 2020-11-20T05:15:01.254+0000 I NETWORK  [listener] connection accepted from 172.22.0.3:37746 #7 (7 connections now open)
mongo_1       | 2020-11-20T05:15:01.256+0000 I NETWORK  [conn7] received client metadata from 172.22.0.3:37746 conn7: { driver: { name: "mongo-java-driver", version: "3.4.                                                                                                                        3-dirty" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "5.4.0-53-generic" }, platform: "Java/Private Build/1.8.0_275-8u275-b01-0ubuntu1~18.04-b01"                                                                                                                         }
mongo_1       | 2020-11-20T05:15:01.270+0000 I NETWORK  [listener] connection accepted from 172.22.0.3:37748 #8 (8 connections now open)
mongo_1       | 2020-11-20T05:15:01.271+0000 I NETWORK  [conn8] received client metadata from 172.22.0.3:37748 conn8: { driver: { name: "mongo-java-driver", version: "3.4.                                                                                                                        3-dirty" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "5.4.0-53-generic" }, platform: "Java/Private Build/1.8.0_275-8u275-b01-0ubuntu1~18.04-b01"                                                                                                                         }
mongo_1       | 2020-11-20T05:15:01.568+0000 I NETWORK  [conn8] end connection 172.22.0.3:37748 (7 connections now open)
mongo_1       | 2020-11-20T05:15:01.572+0000 I NETWORK  [conn7] end connection 172.22.0.3:37746 (6 connections now open)
mongo_1       | 2020-11-20T05:15:01.582+0000 I NETWORK  [listener] connection accepted from 172.22.0.3:37750 #9 (7 connections now open)
mongo_1       | 2020-11-20T05:15:01.583+0000 I NETWORK  [conn9] end connection 172.22.0.3:37750 (6 connections now open)
mongo_1       | 2020-11-20T05:15:02.830+0000 I NETWORK  [conn6] end connection 172.22.0.3:37744 (5 connections now open)
mongo_1       | 2020-11-20T05:15:02.831+0000 I NETWORK  [conn5] end connection 172.22.0.3:37742 (4 connections now open)
controller_1  | Exception in thread "launcher" java.lang.IllegalStateException: Tomcat failed to start up
controller_1  |         at com.ubnt.net.OoOO.ö00000(Unknown Source)
controller_1  |         at com.ubnt.service.B.øO0000(Unknown Source)
controller_1  |         at com.ubnt.ace.Launcher.main(Unknown Source)
controller_1  | Caused by: java.lang.RuntimeException: Web context failed to initialize
controller_1  |         ... 3 more
```

**Comment by jacobalberty** [comment]
Are you pulling `latest` or `6.0.36`?

**Comment by SubtleMuffin** [comment]
> Are you pulling `latest` or `6.0.36`?

latest

**Comment by dailyherold** [comment]
I'm seeing same problem on a fresh 20.04 install. Just got docker configured, ensuring I'm part of the `docker` group. Have tried `latest`, `stable-6`, and `stable-5`. Feels like a docker volume permission issue or SELinux type block, but no proof of either.

**Comment by mvaneijken** [comment]
I'm experiencing the same issue in an existing installation. I seems that it hapend after an automated update to version 6.0.36. 

This is the error reported after starting the container:

`[2020-11-22 12:10:37,542] <docker-entrypoint> Starting unifi controller service.
,Exception in thread "launcher" java.lang.IllegalStateException: Tomcat failed to start up
,	at com.ubnt.net.OoOO.ö00000(Unknown Source)
,	at com.ubnt.service.B.øO0000(Unknown Source)
,	at com.ubnt.ace.Launcher.main(Unknown Source)
,Caused by: java.lang.RuntimeException: Web context failed to initialize
,	... 3 more
,`

**Comment by si458** [comment]
im seeing no issues with numbered tags
ive just updated from 6.0.23 to 6.0.36 in our kubernetes cluster no problems
however i used `jacobalberty/unifi:6.0.36` not the `latest` tag

**Comment by mvaneijken** [comment]
I used tag stable-6 which should be the same as latest I suppose? I've done an explicit deployment of version 6.0.23. That one works fine. I'll try 6.0.36 later and report back.

**Comment by jacobalberty** [comment]
So this is definitely a permission issue, what does the docker-compose from op look like? you should be able to just chown the /unifi volume to match the user in container.

**Comment by r-j-w** [comment]
> So this is definitely a permission issue, what does the docker-compose from op look like? you should be able to just chown the /unifi volume to match the user in container.

I had to `chown` `/unifi/` from root to unifi user. Restarted the container and got some explicit permissions errors.
`find /unifi -user root -exec chown unifi {} \;` and restarting the container cleared everything up..

**Comment by dailyherold** [comment]
Yup, even with a fresh `docker-compose down && docker-compose build --pull && docker-compose up -d` after https://github.com/jacobalberty/unifi-docker/commit/57479165c339e4766b4cd682b9560f05c0ce6cec I had similar problems. Like @r-j-w mentioned, I followed these steps to get things working:
- exec'd into controller using `docker exec -ti -u root unifi_controller /bin/bash`
- ran `find /unifi -user root -exec chown unifi {} \;`
- exited then did a `docker-compose restart`

**Comment by si458** [comment]
@dailyherold i think the line
https://github.com/jacobalberty/unifi-docker/blob/57479165c339e4766b4cd682b9560f05c0ce6cec/Dockerfile#L79
should read `unifi:unifi` not `unifi.unifi`

**Comment by mvaneijken** [comment]
I'm not using docker compose, but following command did the job for me:
```
docker exec -ti unifi bash
chown unifi.unifi -R /unifi 
exit
docker restart unifi
```

Running docker tag stable-6 now.

**Comment by SubtleMuffin** [comment]
> Yup, even with a fresh `docker-compose down && docker-compose build --pull && docker-compose up -d` after [5747916](https://github.com/jacobalberty/unifi-docker/commit/57479165c339e4766b4cd682b9560f05c0ce6cec) I had similar problems. Like @r-j-w mentioned, I followed these steps to get things working:
> 
> * exec'd into controller using `docker exec -ti -u root unifi_controller /bin/bash`
> * ran `find /unifi -user root -exec chown unifi {} \;`
> * exited then did a `docker-compose restart`

@dailyherold Thank you for your suggestions!

Just a FYI -- this permission issue appears in `6.0.22` as well.. though the webpage is normal, but I wasn't able to generate backup file (`There was an error generating a site export file.`). After the above fix (permission issue fixed by `chown`), I am able to generate backup file.

**Comment by jacobalberty** [comment]
@si458 the dot syntax is old but still works the same for this.

I'll update it to colon just so it doesn't become an issue in the future though.

**Comment by okuuva** [comment]
I'm still having this issue with 6.0.43. I recently updated my 5.XX docker-compose setup to :latest and had to manually chown /unifi to unifi-user in controller-container. Luckily this issue thread comes up quite early with "unifi controller docker 404" search in Google. Haven't tried with fresh setup but I don't see why it would be any different there when using compose.

**Comment by jakubmuransky** [comment]
> I'm not using docker compose, but following command did the job for me:
> 
> ```
> docker exec -ti unifi bash
> chown unifi.unifi -R /unifi 
> exit
> docker restart unifi
> ```
> 
> Running docker tag stable-6 now.

This solution works great but you need to use root account  **docker exec -u root -it unifi_controller bash**
Is this error of docker-compose permissions or image ? I am using user:unifi in docker-compose

**Comment by mvaneijken** [comment]
Not that I'm aware of. I'm not running the image itself as a non-root user, maybe that makes it different?

**Comment by pedropombeiro** [comment]
Same thing happened now when moving from 6.1.71 to 6.2...

**Comment by SubtleMuffin** [comment]
> 
> 
> Same thing happened now when moving from 6.1.71 to 6.2...

Ah... thanks for letting us know... better not to upgrade now :(

**Comment by daballiemo** [comment]
Here still exactly the same on a fresh install with latest:

`docker exec -ti unifi bash
chown unifi.unifi -R /usr/lib/unifi 
exit
docker restart unifi`

worked like a charm.

**Comment by ashebanow** [comment]
No need to reopen, but I was having the same issue with the latest version. Checked my permissions and they were correct. Switching to stable-6 fixed everything.
